#a program for simple calculator
#this was completely generated by Bing AI by giving specific prompts

def calculator():
    num1 = float(input("Enter the first number: "))
    print("Select an operation:")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Division")
    operator = input("Enter your choice (1/2/3/4): ")
    num2 = float(input("Enter the second number: "))

    if operator == "1":
        result = num1 + num2
        symbol = "+"
    elif operator == "2":
        result = num1 - num2
        symbol = "-"
    elif operator == "3":
        result = num1 * num2
        symbol = "*"
    elif operator == "4":
        result = num1 / num2
        symbol = "/"
    else:
        print("Invalid operator")
        return

    print(f"{num1} {symbol} {num2} = {result}")

calculator()