#a program for simple calculator
#this was completely generated by Bing AI by giving specific prompts

def calculator():
    print("Select an operation:")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Division")
    print("5. Calculate BMI")
    operator = input("Enter your choice (1/2/3/4/5): ")

    if operator == "5":
        calculate_bmi()
        return

    num1 = float(input("Enter the first number: "))
    num2 = float(input("Enter the second number: "))

    if operator == "1":
        result = num1 + num2
        symbol = "+"
    elif operator == "2":
        result = num1 - num2
        symbol = "-"
    elif operator == "3":
        result = num1 * num2
        symbol = "*"
    elif operator == "4":
        result = num1 / num2
        symbol = "/"
    else:
        print("Invalid operator")
        return

    print(f"{num1} {symbol} {num2} = {result}")

def calculate_bmi():
    weight = float(input("Enter your weight in kilograms: "))
    height = float(input("Enter your height in meters: "))
    bmi = weight / (height ** 2)
    print(f"Your BMI is: {bmi}")

calculator()